# Generated by Django 3.0.5 on 2020-05-04 03:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200504_0338'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_search__34fc30_gin',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='search_vector',
            new_name='search_vector_text',
        ),
        migrations.AddField(
            model_name='question',
            name='search_vector_title',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_title', 'search_vector_text'], name='questions_q_search__d0470c_gin'),
        ),
    ]
