# Generated by Django 3.0.5 on 2020-05-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_new_search_triggers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_search__d0470c_gin',
        ),
        migrations.RemoveField(
            model_name='question',
            name='search_vector_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='search_vector_title',
        ),
    ]
